# Generated by Django 2.2.2 on 2019-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citi',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('start_balance', models.FloatField(default=0)),
                ('end_balance', models.FloatField(default=0)),
                ('inflows', models.FloatField(default=0)),
                ('outflows', models.FloatField(default=0)),
                ('transfer_in', models.FloatField(default=0)),
                ('transfer_out', models.FloatField(default=0)),
                ('depo', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('reconciliation', models.FloatField(default=0)),
            ],
        ),
    ]
