# Generated by Django 2.2.2 on 2019-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20190613_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_number', models.AutoField(primary_key=True, serialize=False)),
                ('deal_date', models.DateField(null=True)),
                ('value_date', models.DateField(null=True)),
                ('deal_kind', models.CharField(choices=[(1, 'DEPO'), (2, 'TXFR'), (1, 'FX_BUY'), (1, 'FX_SELL')], max_length=20, null=True)),
                ('currency_base', models.CharField(choices=[(1, 'PLN'), (2, 'EUR'), (3, 'USD')], max_length=3, null=True)),
                ('currency_side', models.CharField(choices=[(1, 'PLN'), (2, 'EUR'), (3, 'USD')], max_length=3, null=True)),
                ('currency_cross', models.CharField(choices=[(1, 'EUR/PLN'), (2, 'USD/PLN'), (3, 'EUR/USD')], max_length=7, null=True)),
                ('side', models.CharField(choices=[(1, 'BUY'), (2, 'SELL')], max_length=20, null=True)),
                ('counterparty', models.CharField(max_length=30, null=True)),
                ('counterparty_another', models.CharField(max_length=30, null=True)),
                ('amount_in_base_cur', models.FloatField(null=True)),
                ('amount_in_side_cur', models.FloatField(null=True)),
                ('exchange_rate', models.FloatField(null=True)),
                ('interest_rate', models.FloatField(null=True)),
                ('interest_rate_amount', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
