# Generated by Django 2.2.2 on 2019-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20190613_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='counterparty',
            field=models.CharField(choices=[('Citi', 'Citi'), (2, ' mBank'), (3, 'Societe'), (4, 'Santander')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='currency_base',
            field=models.CharField(choices=[('PLN', 'PLN'), (2, 'EUR'), (3, 'USD')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='currency_side',
            field=models.CharField(choices=[('PLN', 'PLN'), (2, 'EUR'), (3, 'USD')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
