# Generated by Django 2.2.2 on 2019-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_auto_20190613_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='deal_kind',
            field=models.CharField(choices=[('DEPO', 'DEPO'), ('TXFR', 'TXFR'), ('FX', 'FX')], max_length=20, null=True),
        ),
    ]
