# Generated by Django 2.2.2 on 2019-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_auto_20190625_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='counterparty',
            field=models.CharField(blank=True, choices=[('Citi', 'Citi'), ('mBank', ' mBank'), ('Societe', 'Societe'), ('Santander', 'Santander')], default='', max_length=30, null=True),
        ),
    ]
