# Generated by Django 2.2.2 on 2019-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0016_auto_20190625_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santander',
            name='depo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='end_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='inflows',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='interest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='outflows',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='reconciliation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='start_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='transfer_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='santander',
            name='transfer_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='depo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='end_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='inflows',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='interest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='outflows',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='reconciliation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='start_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='transfer_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='societe',
            name='transfer_out',
            field=models.FloatField(default=0),
        ),
    ]
