# Generated by Django 2.2.2 on 2019-07-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0018_deals_value_date_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='value_date_expiry',
            new_name='expiry_date',
        ),
    ]
