# Generated by Django 2.2.2 on 2019-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0021_deals_frontoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='fronttime',
            field=models.DateTimeField(null=True),
        ),
    ]
