# Generated by Django 2.2.2 on 2019-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0022_deals_fronttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='backoffice',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='backtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='basis',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='cancel_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='cancel_user',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='comment',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='entity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='middleoffice',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='middletime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='strategy_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
