# Generated by Django 2.2.2 on 2019-07-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0024_auto_20190724_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='entity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
