# Generated by Django 2.2.2 on 2019-09-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0025_auto_20190724_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='citi',
            name='reconciled',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='mbank',
            name='reconciled',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='santander',
            name='reconciled',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='societe',
            name='reconciled',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
