# Generated by Django 2.2.2 on 2019-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0026_auto_20190911_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('inflows', models.FileField(null=True, upload_to='')),
                ('outflows', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
