# Generated by Django 2.2.2 on 2019-11-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0028_eur1m_eur3m_pln1m_pln3m_pln6m_usd3m'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EUR1M',
            new_name='EUR6M',
        ),
    ]
