# Generated by Django 2.2.2 on 2019-11-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0029_auto_20191126_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='EURPLN',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('spot', models.FloatField(default=0)),
                ('on', models.FloatField(default=0)),
                ('tn', models.FloatField(default=0)),
                ('sn', models.FloatField(default=0)),
                ('w1', models.FloatField(default=0)),
                ('w2', models.FloatField(default=0)),
                ('w3', models.FloatField(default=0)),
                ('m1', models.FloatField(default=0)),
                ('m2', models.FloatField(default=0)),
                ('m3', models.FloatField(default=0)),
                ('m4', models.FloatField(default=0)),
                ('m5', models.FloatField(default=0)),
                ('m6', models.FloatField(default=0)),
                ('m9', models.FloatField(default=0)),
                ('m12', models.FloatField(default=0)),
                ('y2', models.FloatField(default=0)),
                ('y5', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='USDPLN',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('spot', models.FloatField(default=0)),
                ('on', models.FloatField(default=0)),
                ('tn', models.FloatField(default=0)),
                ('sn', models.FloatField(default=0)),
                ('w1', models.FloatField(default=0)),
                ('w2', models.FloatField(default=0)),
                ('w3', models.FloatField(default=0)),
                ('m1', models.FloatField(default=0)),
                ('m2', models.FloatField(default=0)),
                ('m3', models.FloatField(default=0)),
                ('m4', models.FloatField(default=0)),
                ('m5', models.FloatField(default=0)),
                ('m6', models.FloatField(default=0)),
                ('m9', models.FloatField(default=0)),
                ('m12', models.FloatField(default=0)),
                ('y2', models.FloatField(default=0)),
            ],
        ),
    ]
