# Generated by Django 2.2.2 on 2019-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0030_eurpln_usdpln'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eurpln',
            name='y5',
        ),
    ]
