# Generated by Django 2.2.2 on 2019-11-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0031_remove_eurpln_y5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eurpln',
            old_name='m12',
            new_name='y1',
        ),
        migrations.RenameField(
            model_name='usdpln',
            old_name='m12',
            new_name='y1',
        ),
    ]
