# Generated by Django 2.2.2 on 2019-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0032_auto_20191129_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='forward_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_kind',
            field=models.CharField(choices=[('DEPO', 'DEPO'), ('TXFR', 'TXFR'), ('FX', 'FX'), ('FWD', 'FWD')], max_length=20, null=True),
        ),
    ]
